apiVersion: v2
name: vault-auth
description: Production-grade JWT authentication microservice
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - authentication
  - jwt
  - security
  - oauth2
  - totp
home: https://github.com/42-v/vault42
sources:
  - https://github.com/42-v/vault42
maintainers:
  - name: V
    email: vault@42-v.com
