-- ============================================================================
-- 041: the admin plane can set a user's roles
-- ============================================================================
--
-- Roles reach auth.users at exactly one place today: POST /admin/users/import,
-- which writes them in the INSERT. After that they are frozen. There is no
-- route, no repository method and no grant that can change a live user's roles,
-- so an operator who imports a user with the wrong roles, or a platform that
-- promotes somebody after the import, has nowhere to go but SQL.
--
-- GET/POST/DELETE /admin/roles is the *catalog* -- the set of names that exist.
-- It has never been the assignment.
--
-- vault_admin holds SELECT on auth.users (001:455) and UPDATE on exactly three
-- columns: locked_until and failed_login_count (001:456) and must_reset_password
-- (039:141). 009 granted six more; 015:112 revoked all six and 015:105-108
-- records that what remains is the two from 001. PostgreSQL checks the column
-- privilege on every target an UPDATE names, so without this grant a
-- roles-writing statement fails with 42501 in any deployment running as the
-- real role -- and passes in the admin-plane tests, which drive the owner pool
-- where the grant is irrelevant. That is the shape 040 was written to fix for
-- refresh_tokens, one table over.
--
-- Column-scoped, like 039 and 040, and for the reason 037 records: a
-- column-level REVOKE is a silent no-op when a table-level grant exists, so the
-- absence of a table-level UPDATE here is what makes the narrow grant mean
-- something. vault_admin cannot reach email, password_hash, deleted or
-- mfa_required through this.
--
-- Not granted to vault_app. The main binary reads roles at token issuance and
-- has never written them; nothing on that side should start.
--
-- What this deliberately does not do is constrain the values. Migration 003
-- states there is no DB-level CHECK on role strings, and 005 keeps the catalog
-- in its own table rather than as an enum, so the invariants -- name shape,
-- catalog membership, admin-tier names refused -- live in Go where the error
-- messages are. A CHECK here would answer 23514 to a caller that deserves a
-- 400 naming the role.
--
-- Written bare rather than wrapped in a pg_roles guard, which is what 039 does
-- for the nearest precedent there is: a column grant on auth.users to
-- vault_admin, two lines at column zero (039:140-141). GRANT is idempotent by
-- definition and 001 creates both roles unconditionally, so the guard buys
-- nothing.
--
-- It also costs something, and 015:52-57 is where that is written down.
-- applyRealGrants -- the fixture that re-applies these statements and connects
-- as the real role -- splits each file on ';' and keeps a statement only when it
-- starts with GRANT or REVOKE. A grant inside a DO block yields a first
-- statement beginning with DO, so it is skipped: the privilege suite would go on
-- exercising a model that never received this grant, and PUT /admin/users/{id}
-- /roles would answer 42501 in a real deployment while the suite stayed green.
-- That is the same shape as the erasure bug the fixture was built for, and it is
-- why 040's DO block is worth revisiting separately.

GRANT UPDATE (roles) ON auth.users TO vault_admin;
