#!/usr/bin/env bash
# The root VERSION file is the single source of truth for the release version.
# This script is the only thing that writes the copies of it that live in
# manifests, and the only thing that knows where all of them are.
#
#   scripts/version-bump.sh 1.0.0     write VERSION and every copy
#   scripts/version-bump.sh           re-propagate the current VERSION
#   scripts/version-bump.sh --check   report disagreements, change nothing, exit 1
#   scripts/version-bump.sh --list    print every location and its current value
#   scripts/version-bump.sh --ldflags print the Go ldflags that stamp this version
#
# Go binaries carry the version through -ldflags rather than a checked-in
# constant, so there is nothing in Go source to rewrite:
#   - Dockerfile{,.bridge,.admin-gateway} take it as the VERSION build arg,
#     which .github/workflows/release.yml fills from the release tag.
#   - .goreleaser.yaml derives it from the tag as {{ .Version }}.
#   - local builds get it from --ldflags below.
# scripts/release-check.sh --version-only asserts the tag and VERSION agree, so
# the ldflags value can never diverge from the manifests this script writes.
set -euo pipefail
cd "$(dirname "$0")/.."

SEMVER='[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?'

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Each rule is LABEL::FILE::PREFIX::SUFFIX, where PREFIX and SUFFIX are extended
# regexes that bracket the version on its line. One list drives --check, --list
# and the rewrite, so a location can never be checked but not written.
RULES=(
  "chart version::charts/vault/Chart.yaml::^version: ::\$"
  "chart appVersion::charts/vault/Chart.yaml::^appVersion: \"::\"\$"
  "vue package::packages/vue/package.json::^  \"version\": \"::\",?\$"
  "web package::web/package.json::^  \"version\": \"::\",?\$"
  "root package::package.json::^  \"version\": \"::\",?\$"
  "badges.json::docs/badges.json::\"version\": \"::\""
  "AspNetCore csproj::packages/dotnet/src/Vault42.AspNetCore/Vault42.AspNetCore.csproj::<Version>::</Version>"
  "Blazor csproj::packages/dotnet/src/Vault42.Blazor/Vault42.Blazor.csproj::<Version>::</Version>"
  "site helm command::site/index.html::--set image\.tag=::"
  "site footer::site/index.html::vault42 v::"
)

# The root package.json is `private: true` and carries no version field. Every
# other rule is required: a location that stops matching is a location that has
# silently dropped out of the propagation set, which is the failure mode this
# script exists to prevent.
OPTIONAL_LABELS="root package"

read_version_file() {
  [ -f VERSION ] || { echo "VERSION file is missing" >&2; exit 1; }
  tr -d '[:space:]' < VERSION
}

# rule_values LABEL FILE PREFIX SUFFIX -> every version found by that rule, one per line
rule_values() {
  local file="$2" prefix="$3" suffix="$4"
  [ -f "$file" ] || return 0
  sed -nE "s%^.*${prefix}(${SEMVER})${suffix}.*\$%\1%p" "$file"
}

split_rule() {
  RULE_LABEL=${1%%::*}
  local rest=${1#*::}
  RULE_FILE=${rest%%::*}
  rest=${rest#*::}
  RULE_PREFIX=${rest%%::*}
  RULE_SUFFIX=${rest#*::}
}

cmd_list() {
  local rule
  for rule in "${RULES[@]}"; do
    split_rule "$rule"
    local found
    found=$(rule_values "$RULE_LABEL" "$RULE_FILE" "$RULE_PREFIX" "$RULE_SUFFIX" | sort -u | paste -sd, -)
    printf '%-20s %-62s %s\n' "$RULE_LABEL" "$RULE_FILE" "${found:-<absent>}"
  done
}

rule_is_optional() {
  case " $OPTIONAL_LABELS " in *" $1 "*) return 0 ;; *) return 1 ;; esac
}

cmd_check() {
  local want="$1" bad=0 rule
  echo "VERSION = $want"
  for rule in "${RULES[@]}"; do
    split_rule "$rule"
    if [ ! -f "$RULE_FILE" ]; then
      rule_is_optional "$RULE_LABEL" \
        && { printf "${YELLOW}SKIP${NC} %-20s %s (no such file)\n" "$RULE_LABEL" "$RULE_FILE"; continue; }
      printf "${RED}GONE${NC} %-20s %s is missing\n" "$RULE_LABEL" "$RULE_FILE"
      bad=1
      continue
    fi
    local found
    found=$(rule_values "$RULE_LABEL" "$RULE_FILE" "$RULE_PREFIX" "$RULE_SUFFIX" | sort -u)
    if [ -z "$found" ]; then
      rule_is_optional "$RULE_LABEL" \
        && { printf "${YELLOW}SKIP${NC} %-20s %s (no version string)\n" "$RULE_LABEL" "$RULE_FILE"; continue; }
      printf "${RED}GONE${NC} %-20s no version string in %s\n" "$RULE_LABEL" "$RULE_FILE"
      bad=1
      continue
    fi
    if [ "$found" = "$want" ]; then
      printf "${GREEN}OK${NC}   %-20s %s\n" "$RULE_LABEL" "$found"
    else
      printf "${RED}DIFF${NC} %-20s %s (want %s) in %s\n" \
        "$RULE_LABEL" "$(echo "$found" | paste -sd, -)" "$want" "$RULE_FILE"
      bad=1
    fi
  done
  return $bad
}

# badges.json is regenerated by scripts/readme-gen.sh, which does not know about
# the release version. Seed the key so the rewrite rule below has a line to hit.
seed_badges_version() {
  local want="$1"
  [ -f docs/badges.json ] || return 0
  grep -q '"version"' docs/badges.json && return 0
  python3 - "$want" <<'PY'
import json, sys
from collections import OrderedDict
p = "docs/badges.json"
with open(p) as fh:
    data = json.load(fh, object_pairs_hook=OrderedDict)
merged = OrderedDict([("schemaVersion", data.pop("schemaVersion", 1)), ("version", sys.argv[1])])
merged.update(data)
with open(p, "w") as fh:
    json.dump(merged, fh, indent=2)
    fh.write("\n")
PY
}

cmd_write() {
  local want="$1" rule
  printf '%s\n' "$want" > VERSION
  seed_badges_version "$want"
  for rule in "${RULES[@]}"; do
    split_rule "$rule"
    if [ ! -f "$RULE_FILE" ]; then
      rule_is_optional "$RULE_LABEL" \
        && { printf "${YELLOW}SKIP${NC} %-20s %s (no such file)\n" "$RULE_LABEL" "$RULE_FILE"; continue; }
      echo -e "${RED}FAIL${NC} $RULE_LABEL: $RULE_FILE is missing"
      exit 1
    fi
    local before after
    before=$(rule_values "$RULE_LABEL" "$RULE_FILE" "$RULE_PREFIX" "$RULE_SUFFIX" | sort -u | paste -sd, -)
    if [ -z "$before" ]; then
      rule_is_optional "$RULE_LABEL" \
        && { printf "${YELLOW}SKIP${NC} %-20s %s (no version string)\n" "$RULE_LABEL" "$RULE_FILE"; continue; }
      echo -e "${RED}FAIL${NC} $RULE_LABEL: no version string in $RULE_FILE"
      exit 1
    fi
    sed -i -E "s%(${RULE_PREFIX})${SEMVER}(${RULE_SUFFIX})%\1${want}\3%g" "$RULE_FILE"
    after=$(rule_values "$RULE_LABEL" "$RULE_FILE" "$RULE_PREFIX" "$RULE_SUFFIX" | sort -u | paste -sd, -)
    [ "$after" = "$want" ] || { echo -e "${RED}FAIL${NC} $RULE_LABEL still reads '$after' in $RULE_FILE"; exit 1; }
    printf "${GREEN}SET${NC}  %-20s %-14s %s\n" "$RULE_LABEL" "$before -> $want" "$RULE_FILE"
  done
  echo -e "\n${GREEN}VERSION = $want${NC}; run scripts/release-check.sh --version-only $want to confirm."
}

cmd_ldflags() {
  local want="$1" commit build_time
  commit=$(git rev-parse HEAD 2>/dev/null || echo unknown)
  build_time=$(git show -s --format=%cI HEAD 2>/dev/null || date -u +%Y-%m-%dT%H:%M:%SZ)
  printf -- '-s -w -X main.Version=%s -X main.GitCommit=%s -X main.BuildTime=%s\n' \
    "$want" "$commit" "$build_time"
}

case "${1-}" in
  --list)
    cmd_list
    ;;
  --check)
    cmd_check "$(read_version_file)"
    ;;
  --ldflags)
    cmd_ldflags "$(read_version_file)"
    ;;
  -h | --help)
    sed -nE '2,20s/^# ?//p' "$0"
    ;;
  "")
    cmd_write "$(read_version_file)"
    ;;
  *)
    printf '%s' "$1" | grep -qE "^${SEMVER}\$" \
      || { echo "not a semantic version: $1" >&2; exit 1; }
    cmd_write "$1"
    ;;
esac
