package ipintel

import _ "embed"

// embeddedBlob is the built-in IP-intelligence table, regenerated by
// scripts/gen-ipintel.py. It is embedded so the static binary is
// self-contained; VAULT_IPINTEL_DATA can override it at runtime.
//
//go:embed data/ipintel.bin
var embeddedBlob []byte
