package spec_test

import (
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The C# SDK hard-codes the server's paths, and nothing compared them to it.
//
// route_drift_test.go is thorough in one direction and blind in another: it
// parses internal/server/server.go and internal/adminapi/router.go with go/ast
// and holds them against the inventories in docs/api.md and docs/spec.md, in
// both directions. It never mentions the .NET packages. So the Blazor client's
// six default paths and the JWKS suffix the AspNetCore package appends were
// free to describe a server that no longer exists.
//
// The failure that produces is quiet and total. Rename POST /auth/refresh and
// the Go tests stay green, the docs are regenerated by the same gate that
// forced the rename, and every Blazor application built on this SDK starts
// getting 404s on token refresh -- which surfaces as users being silently
// signed out when their access token expires, not as a build error. The SDK
// ships to consumers, so the rename reaches them before the mismatch does.
//
// It is the A1 defect -- broken object-level authorization through a path the
// server does not serve the way the client thinks -- reachable by a rename
// nobody would think to check.

var (
	// `public string RefreshPath { get; set; } = "/auth/refresh";`
	csharpPathDefault = regexp.MustCompile(
		`(?m)^\s*public\s+string\s+(\w+)\s*\{\s*get;\s*set;\s*\}\s*=\s*"(/[^"]*)"\s*;`)

	// `options.Authority.TrimEnd('/') + "/.well-known/jwks.json"`
	csharpAppendedPath = regexp.MustCompile(`TrimEnd\('/'\)\s*\+\s*"(/[^"]+)"`)
)

// csharpDeclaredPaths reads every server path the .NET packages hold as a
// literal, keyed by the member that carries it.
//
// Two shapes, because the SDK writes them two ways: a settable default on the
// options object, and a suffix concatenated onto the configured Authority.
func csharpDeclaredPaths(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}

	blazor := filepath.Join("packages", "dotnet", "src", "Vault42.Blazor", "VaultBlazorOptions.cs")
	for _, m := range csharpPathDefault.FindAllStringSubmatch(commentFreeSource(t, filepath.Join(root, blazor)), -1) {
		out[blazor+":"+m[1]] = m[2]
	}

	jwks := filepath.Join("packages", "dotnet", "src", "Vault42.AspNetCore", "VaultJwksManager.cs")
	for _, m := range csharpAppendedPath.FindAllStringSubmatch(commentFreeSource(t, filepath.Join(root, jwks)), -1) {
		out[jwks+":Authority+suffix"] = m[1]
	}

	if len(out) == 0 {
		t.Fatal("no server path found in the .NET packages. If they stopped hard-coding paths " +
			"this gate can go, but it must not be left matching nothing: a regex that finds " +
			"zero paths agrees with every server.")
	}
	return out
}

// notAServerRoute is the set this gate deliberately does not check, and why.
//
// Listed rather than pattern-matched, so adding a member that happens to start
// with a slash cannot silently join it.
var notAServerRoute = map[string]string{
	"PostLogoutRedirectUri": "a path in the CONSUMER's application, where the browser lands after " +
		"logout. The Vault server never serves it and must not be expected to.",
}

// RedirectUri is not listed, and the reason is worth recording because it looks
// like an omission. It defaults to string.Empty rather than to a path, so the
// regex above never sees it -- and its own doc comment says the server does not
// honor it either way. Exempting it would have put an entry in that list
// describing something the gate could not have flagged.

func TestCSharpSDKPointsAtRoutesTheServerRegisters(t *testing.T) {
	root := repoRoot(t)
	registered, _ := implementedRoutes(t, root)

	// The SDK stores a path without a method, so the question this can answer is
	// whether the server serves that path at all, under any verb.
	paths := map[string]bool{}
	for r := range registered {
		paths[r.path] = true
	}

	declared := csharpDeclaredPaths(t, root)
	keys := make([]string, 0, len(declared))
	for k := range declared {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	checked := 0
	for _, key := range keys {
		member := key[strings.LastIndex(key, ":")+1:]
		if _, skip := notAServerRoute[member]; skip {
			continue
		}
		checked++
		if !paths[declared[key]] {
			t.Errorf("%s holds %q and no route in internal/server or internal/adminapi serves it.\n"+
				"A Blazor application built on this SDK would get a 404 there. If the server "+
				"path moved, move this default with it; if the member is not a server path, "+
				"add it to notAServerRoute with the reason.",
				key, declared[key])
		}
	}

	// A gate that checked nothing would pass. The count is asserted so a regex
	// that stops matching, or an exemption list that grows to cover everything,
	// fails here instead of going quiet.
	if checked < 5 {
		t.Errorf("only %d SDK paths were checked, which is fewer than this SDK has ever "+
			"declared. Either the regexes stopped matching or notAServerRoute has grown to "+
			"swallow the surface it was meant to carve two exceptions out of.", checked)
	}
}

// The other direction is not symmetric and should not be: the server serves far
// more than the SDK wraps. What IS worth holding is that the exemptions still
// describe members that exist, so the list cannot rot into a description of a
// file that has moved on.
func TestTheCSharpSDKExemptionsStillNameRealMembers(t *testing.T) {
	root := repoRoot(t)
	// Comment-free, because a member named only in a doc comment would satisfy
	// this and certify a claim the file does not make. VaultBlazorOptions.cs is
	// heavily documented, and it names RedirectUri and the callback in prose.
	blazor := commentFreeSource(t, filepath.Join(root,
		"packages", "dotnet", "src", "Vault42.Blazor", "VaultBlazorOptions.cs"))

	for member, why := range notAServerRoute {
		if !strings.Contains(blazor, "public string "+member) {
			t.Errorf("notAServerRoute exempts %q (%s) and VaultBlazorOptions.cs no longer "+
				"declares it. An exemption for something that is not there stops recording a "+
				"decision and starts hiding whatever takes its place.", member, why)
		}
	}
}
