// docs/deps.md completeness gate.
//
// The maintainers table is generated by scripts/readme-gen.sh from one GitHub
// API call per owner. api.github.com allows 60 unauthenticated calls an hour,
// and past that it answers 403. curl -f treated that refusal the same as a
// missing account, so a rate-limited run published
//
//	| [tinylib](https://github.com/tinylib) | — | msgp | — | — | — |
//
// for a three-repo organization that has been on GitHub since 2015. Nothing
// failed. The row is well-formed, the table still renders, and the reader has
// no way to tell "we could not reach GitHub" from "this dependency is
// maintained by nobody you can look up" -- which is the more alarming reading
// and the wrong one.
//
// The generator now refuses to write on a rate limit. This gate is the other
// half: it fails if a placeholder row reaches the tree anyway, whether from an
// older generator, a hand-edit, or a future change that reintroduces the
// fallback. It is offline and deterministic; it asks nothing of GitHub.
package spec_test

import (
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"testing"
)

// absentFromGitHub are owners whose row may legitimately carry placeholders,
// because the account really is not on GitHub under that name.
//
// Empty on purpose. Every placeholder seen so far was this script failing to
// reach GitHub, not a fact about the dependency. An entry here is a claim that
// somebody went and looked, so it costs a sentence saying so.
var absentFromGitHub = map[string]string{}

const depsDoc = "docs/deps.md"

// maintainerRow matches a generated row: | [owner](url) | Type | pkgs | repos | followers | since |
var maintainerRow = regexp.MustCompile(`^\|\s*\[([^\]]+)\]\([^)]*\)\s*\|(.*)\|\s*$`)

func TestDepsMaintainerTableHasNoUnreachedRows(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, depsDoc))
	if err != nil {
		t.Fatalf("read %s: %v", depsDoc, err)
	}

	rows := maintainerRows(t, string(raw))

	// Floor first. A parser that matches nothing reports no placeholders, which
	// is indistinguishable from a table that is complete.
	if len(rows) < 5 {
		t.Fatalf("%s: parsed %d maintainer rows, expected at least 5 -- the table "+
			"format changed and this gate is no longer reading it", depsDoc, len(rows))
	}

	for _, r := range rows {
		if why, ok := absentFromGitHub[r.owner]; ok {
			if strings.TrimSpace(why) == "" {
				t.Errorf("absentFromGitHub[%q] has no reason", r.owner)
			}
			continue
		}
		var blank []string
		for i, cell := range r.cells {
			if cell == "—" || cell == "-" || cell == "" {
				blank = append(blank, maintainerColumns[i])
			}
		}
		if len(blank) > 0 {
			t.Errorf("%s: %s has no %s. That is what the generator writes when it "+
				"cannot reach GitHub, and it reads as a fact about the dependency. "+
				"Re-run scripts/readme-gen.sh (set GITHUB_TOKEN if it rate-limits), "+
				"or add %s to absentFromGitHub with what you found when you looked.",
				depsDoc, r.owner, strings.Join(blank, " or "), r.owner)
		}
	}
}

// TestDepsMaintainerHeadlineMatchesTheTable keeps the sentence above the table
// honest. It is written by the same run that writes the rows, so it can only go
// wrong by hand -- which is exactly how the route count in README.md went wrong.
func TestDepsMaintainerHeadlineMatchesTheTable(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, depsDoc))
	if err != nil {
		t.Fatalf("read %s: %v", depsDoc, err)
	}
	text := string(raw)

	headline := regexp.MustCompile(`(?m)^(\d+) maintainers behind`).FindStringSubmatch(text)
	if headline == nil {
		t.Fatalf("%s: no \"N maintainers behind\" headline -- either it was removed "+
			"or reworded, and this gate cannot see the claim it is checking", depsDoc)
	}
	claimed, err := strconv.Atoi(headline[1])
	if err != nil {
		t.Fatalf("parse headline count %q: %v", headline[1], err)
	}

	if got := len(maintainerRows(t, text)); got != claimed {
		t.Errorf("%s says %d maintainers and the table has %d rows", depsDoc, claimed, got)
	}
}

var maintainerColumns = []string{"type", "repo count", "followers badge", "join date"}

type maintainerEntry struct {
	owner string
	cells []string // type, repos, followers, since -- packages is dropped, it is local
}

// maintainerRows pulls the rows out of the Maintainers section only. deps.md has
// three other tables and matching all of them would make the floor meaningless.
func maintainerRows(t *testing.T, text string) []maintainerEntry {
	t.Helper()

	_, after, found := strings.Cut(text, "\n## Maintainers\n")
	if !found {
		t.Fatalf("%s: no \"## Maintainers\" section", depsDoc)
	}
	if next, _, ok := strings.Cut(after, "\n## "); ok {
		after = next
	}

	lines := strings.Split(after, "\n")
	out := make([]maintainerEntry, 0, len(lines))
	for _, line := range lines {
		m := maintainerRow.FindStringSubmatch(line)
		if m == nil {
			continue
		}
		cells := strings.Split(m[2], "|")
		if len(cells) != 5 {
			t.Fatalf("%s: row for %s has %d cells after the creator, expected 5:\n%s",
				depsDoc, m[1], len(cells), line)
		}
		for i := range cells {
			cells[i] = strings.TrimSpace(cells[i])
		}
		// cells[1] is the package list, which is read off go.mod and is never
		// affected by whether GitHub answered.
		out = append(out, maintainerEntry{
			owner: m[1],
			cells: []string{cells[0], cells[2], cells[3], cells[4]},
		})
	}
	if len(out) == 0 {
		t.Fatalf("%s: Maintainers section parsed to zero rows", depsDoc)
	}
	return out
}
