{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository | default "redis" }}:{{ .Values.redis.image.tag | default "7-alpine" }}"
          ports:
            - containerPort: 6379
          args:
            - "--maxmemory"
            - "{{ .Values.redis.maxMemory | default "64mb" }}"
            - "--maxmemory-policy"
            - "allkeys-lru"
            {{- if .Values.secrets.keys.redisPassword }}
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            {{- end }}
          {{- if .Values.secrets.keys.redisPassword }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vault.secretName" . }}
                  key: {{ .Values.secrets.keys.redisPassword }}
          {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  selector:
    app: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
