{{- if .Values.seed.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vault.fullname" . }}-seed
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
data:
  seed.json: |
    {{ dict "clients" .Values.seed.clients "users" .Values.seed.users | toJson }}
{{- end }}
